spring.application.name=RestAPI-github
spring.datasource.url=jdbc:mysql://host.docker.internal:3307/spring_RestAPI_2
spring.datasource.username=root
spring.datasource.password=fighter

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

